# Generated by Django 2.2 on 2019-04-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_de_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Usuário',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
