# Generated by Django 2.2 on 2019-05-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_de_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Usuário',
                'verbose_name_plural': 'Tipo de Usuário',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id_de_Usuario', models.CharField(blank=True, default='', max_length=100, verbose_name='Id de Usuário')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('tipo_de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.Tipo_de_Usuario', verbose_name='Tipo de Usuário')),
            ],
            options={
                'verbose_name': 'Usuários',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
