# Generated by Django 2.2 on 2019-06-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_de_usuario',
            new_name='tipoUsuario',
        ),
    ]
