# Generated by Django 2.2 on 2019-04-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0002_usuario_tipo_de_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.Tipo_de_Usuario'),
        ),
    ]
