# Generated by Django 2.2 on 2019-05-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Usuario',
            fields=[
                ('Id_Card', models.CharField(max_length=100, verbose_name='Id da Carteirinha')),
                ('horarioEntrada', models.DateTimeField(verbose_name='Horário de Entrada')),
                ('horarioSaida', models.DateTimeField(verbose_name='Horário de Saída')),
                ('Status', models.IntegerField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Log de Usuário',
                'verbose_name_plural': 'Log de Usuários',
            },
        ),
    ]
