# Generated by Django 2.2 on 2019-06-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log_Usuario',
        ),
    ]
