# Generated by Django 2.2 on 2019-06-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mail', '0002_delete_log_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Card', models.CharField(max_length=100)),
                ('Status', models.IntegerField()),
                ('Entrou', models.BooleanField()),
                ('Data_ano', models.IntegerField()),
                ('Data_mes', models.IntegerField()),
                ('Data_dia', models.IntegerField()),
                ('Data_hora', models.IntegerField()),
                ('Data_minuto', models.IntegerField()),
                ('Data_segundo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Log de Usuário',
                'verbose_name_plural': 'Log de Usuários',
            },
        ),
    ]
